#!/bin/bash
#SBATCH --job-name=nmmaGRBonlyAnalysis.job
#SBATCH --output=nmmaGRBonlyAnalysis%A_%a.out
#SBATCH --error=nmmaGRBonlyAnalysis%A_%a.err
#SBATCH -p shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=96G
#SBATCH --time=00:10:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=thomas.hussenot@ijclab.in2p3.fr
#SBATCH -A umn131
#SBATCH --export=ALL
module purge
module load sdsc cpu/0.15.4 gcc/10.2.0 intel-mpi/2019.8.254
module load anaconda3
ls /home/thussenot/.conda/envs/nmma
conda activate nmma
light_curve_analysis --model TrPi2018 --outdir outdir --label GRB211211A --prior ./TrPi2018GRB211211A.prior --conditional-gaussian-prior-thetaObs --conditional-gaussian-prior-N-sigma 1 --tmin 0.01 --tmax 10 --dt 0.01 --error-budget 1 --nlive 2048 --Ebv-max 0 --trigger-time 59559.54791666667 --data ../../../GRB211211A.txt --plot --xlim 0,14 --ylim 26,16

